In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns = ['cgap','profile','placed'])

In [3]:
df

cgap  profile  placed
0     8        8       1
1     7        9       1
2     6       10       0
3     5        5       0

In [4]:
# here using the keras 
import tensorflow
from tensorflow import keras 
from keras import Sequential
from keras.layers import Dense 

In [6]:
model =  Sequential()

model.add(Dense(2,activation = 'sigmoid',input_dim =2))
model.add(Dense(1,activation = 'sigmoid'))

x:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[0.70452094, 0.46024847],
        [0.73598325, 0.7789875 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.53902245],
        [1.0056213 ]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
# here we using the simller code  # this is using only for the one time in the code
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.],dtype = np.float32),
                np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.],dtype = np.float32)]

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'binary_crossentropy',optimizer = optimizer)

In [17]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs = 50,verbose = 1,batch_size = 1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.6719
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6712 
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6730 
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7176 
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.6733 
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7328 
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7026 
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6717 
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6571 
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6563 
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.7300 
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7131 
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7022 
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6579 
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7311 
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━

In [18]:
model.get_weights()

[array([[0.10051902, 0.10051902],
        [0.08633357, 0.08633357]], dtype=float32),
 array([-0.03065562, -0.03065562], dtype=float32),
 array([[0.09223358],
        [0.09223358]], dtype=float32),
 array([-0.01406348], dtype=float32)]