In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]] ,columns = ['cgpa','profile_scor','lpa'])

In [3]:
df 

cgpa  profile_scor  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [4]:
import tensorflow 
from tensorflow import keras 
from keras import Sequential
from keras.layers import Dense 

In [6]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim = 2))
model.add(Dense(1,activation = 'linear'))

x:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
# here keras randomly weihts intizatied
model.get_weights()   # here using the keras

[array([[-0.5581652 , -0.34103024],
        [ 0.8333181 ,  0.91711175]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.01612604],
        [-1.04655   ]], dtype=float32),
 array([0.], dtype=float32)]

In [15]:
# here we using the simller code 
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.],dtype = np.float32),
                np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([0.],dtype = np.float32)]

In [16]:
model.set_weights(new_weights)

In [18]:
#  here we get new weight form above 
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer = keras.optimizers.Adam(learning_rate= 0.001)
model.compile(loss = 'mean_squared_error',optimizer = optimizer)

In [20]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs = 75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 31.1240
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23.2841 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.1295 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.0865 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.1426 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.8080 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.4563 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.5098 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.3480 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 27.6896 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.1494 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.1489 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.9749 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.0635 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 20.5282
Epoch 16/75
4/4 ━━━━━

In [21]:
model.get_weights()

[array([[0.3735405 , 0.3735405 ],
        [0.36547452, 0.36547452]], dtype=float32),
 array([0.27222937, 0.27222937], dtype=float32),
 array([[0.37282887],
        [0.37282887]], dtype=float32),
 array([0.20472106], dtype=float32)]